CREATE TABLE `pi_forms` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`tourdate_id` INT NULL DEFAULT '0',
	`pif_number` INT NULL DEFAULT NULL,
	`group_name` VARCHAR(225) NULL DEFAULT NULL,
	`leader_id` INT NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `accomodations` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pi_form_id` INT NOT NULL,
	`hotel_id` INT NULL DEFAULT NULL,
	`check_in` DATE NULL DEFAULT NULL,
	`check_out` DATE NULL DEFAULT NULL,
	`single` INT NULL DEFAULT '0',
	`double` INT NULL DEFAULT '0',
	`triple` INT NULL DEFAULT '0',
	`quad` INT NULL DEFAULT '0',
	`quint` INT NULL DEFAULT '0',
	`sext` INT NULL DEFAULT '0',
	`booked_by` VARCHAR(225) NULL DEFAULT '0',
	`entry_by` INT NULL DEFAULT '0',
	`owner_id` INT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
);
CREATE TABLE `ziarahs` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pi_form_id` INT NOT NULL,
	`city` VARCHAR(225) NULL DEFAULT NULL,
	`date` DATE NULL DEFAULT NULL,
	`time` TIME NULL DEFAULT NULL,
	`transport` INT NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `transportations` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pi_form_id` INT NOT NULL,
	`from` VARCHAR(225) NULL DEFAULT NULL,
	`to` VARCHAR(225) NULL DEFAULT NULL,
	`date` DATE NULL DEFAULT NULL,
	`time` TIME NULL DEFAULT NULL,
	`remarks` VARCHAR(225) NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `local_contacts` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pi_form_id` INT NOT NULL,
	`name` VARCHAR(225) NULL DEFAULT NULL,
	`contact` VARCHAR(225) NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `piform_reference` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pi_form_id` INT NOT NULL,
	`reference` VARCHAR(225) NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
