CREATE TABLE `def_supplier_services` (
	`id` INT NOT NULL,
	`name` VARCHAR(225) NULL DEFAULT NULL,
	`description` LONGTEXT NULL DEFAULT NULL,
	`start_date` DATE NULL DEFAULT NULL,
	`end_date` DATE NULL DEFAULT NULL,
	`price` DECIMAL(16,2) NULL DEFAULT NULL,
	`min_quantity` INT NULL DEFAULT NULL,
	`max_quantity` INT NULL DEFAULT NULL,
	`document` VARCHAR(225) NULL DEFAULT NULL,
	`supplier_id` INT NULL DEFAULT NULL,
	`entry_by` INT NULL DEFAULT NULL,
	`owner_id` INT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);
ALTER TABLE `def_supplier_services`
	ADD COLUMN `status` INT(11) NULL DEFAULT NULL AFTER `supplier_id`;
ALTER TABLE `def_supplier_services`
	CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
